#!/usr/bin/env python3
#
# CONSTANTS
#

from typing import Any


### PROJECT CONSTANTS ###

cycle: str = "2020"
yyyy: str = "2022"
yy: str = "22"
plan_type: str = "Congress"

study_states: list[str] = [
    "AL",
    "AZ",
    "AR",
    "CA",
    "CO",
    "CT",
    "FL",
    "GA",
    "IL",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "MD",
    "MA",
    "MI",
    "MN",
    "MS",
    "MO",
    "NE",
    "NV",
    "NJ",
    "NM",
    "NY",
    "NC",
    "OH",
    "OK",
    "OR",
    "PA",
    "SC",
    "TN",
    "TX",
    "UT",
    "VA",
    "WA",
    "WI",
]  # 37 states with > 2 congressional districts


### ENVIRONMENT CONSTANTS ###

rawdata_dir: str = "../../../local/pg/rawdata"
data_dir: str = "data"
temp_dir: str = "temp"
results_dir: str = "results"
content_dir: str = "content"


def unit_id(units: str) -> str:
    if units in ["block", "state"]:
        return "GEOID20"
    if units in ["bg", "tract"]:
        return "GEOID"
    raise ValueError(f"Invalid units: {units}")


### STATE META DATA ###

# State code helpers copied from dra2020/data_tools/


def make_state_codes() -> dict[str, str]:
    codes: dict[str, str] = {
        "AL": "01",
        "AK": "02",
        "AZ": "04",
        "AR": "05",
        "CA": "06",
        "CO": "08",
        "CT": "09",
        "DE": "10",
        "DC": "11",
        "FL": "12",
        "GA": "13",
        "HI": "15",
        "ID": "16",
        "IL": "17",
        "IN": "18",
        "IA": "19",
        "KS": "20",
        "KY": "21",
        "LA": "22",
        "ME": "23",
        "MD": "24",
        "MA": "25",
        "MI": "26",
        "MN": "27",
        "MS": "28",
        "MO": "29",
        "MT": "30",
        "NE": "31",
        "NV": "32",
        "NH": "33",
        "NJ": "34",
        "NM": "35",
        "NY": "36",
        "NC": "37",
        "ND": "38",
        "OH": "39",
        "OK": "40",
        "OR": "41",
        "PA": "42",
        "RI": "44",
        "SC": "45",
        "SD": "46",
        "TN": "47",
        "TX": "48",
        "UT": "49",
        "VT": "50",
        "VA": "51",
        "WA": "53",
        "WV": "54",
        "WI": "55",
        "WY": "56",
        "PR": "72",
    }
    return codes


def make_state_names() -> dict[str, str]:
    names: dict[str, str] = {
        "AL": "Alabama",
        "AK": "Alaska",
        "AZ": "Arizona",
        "AR": "Arkansas",
        "CA": "California",
        "CO": "Colorado",
        "CT": "Connecticut",
        "DE": "Delaware",
        "DC": "District of Columbia",
        "FL": "Florida",
        "GA": "Georgia",
        "HI": "Hawaii",
        "ID": "Idaho",
        "IL": "Illinois",
        "IN": "Indiana",
        "IA": "Iowa",
        "KS": "Kansas",
        "KY": "Kentucky",
        "LA": "Louisiana",
        "ME": "Maine",
        "MD": "Maryland",
        "MA": "Massachusetts",
        "MI": "Michigan",
        "MN": "Minnesota",
        "MS": "Mississippi",
        "MO": "Missouri",
        "MT": "Montana",
        "NE": "Nebraska",
        "NV": "Nevada",
        "NH": "New Hampshire",
        "NJ": "New Jersey",
        "NM": "New Mexico",
        "NY": "New York",
        "NC": "North Carolina",
        "ND": "North Dakota",
        "OH": "Ohio",
        "OK": "Oklahoma",
        "OR": "Oregon",
        "PA": "Pennsylvania",
        "RI": "Rhode Island",
        "SC": "South Carolina",
        "SD": "South Dakota",
        "TN": "Tennessee",
        "TX": "Texas",
        "UT": "Utah",
        "VT": "Vermont",
        "VA": "Virginia",
        "WA": "Washington",
        "WV": "West Virginia",
        "WI": "Wisconsin",
        "WY": "Wyoming",
        "PR": "Puerto Rico",
    }
    return names


def make_state_names_nospace() -> dict[str, str]:
    names: dict[str, str] = {
        "AL": "Alabama",
        "AK": "Alaska",
        "AZ": "Arizona",
        "AR": "Arkansas",
        "CA": "California",
        "CO": "Colorado",
        "CT": "Connecticut",
        "DE": "Delaware",
        "DC": "DistrictOfColumbia",
        "FL": "Florida",
        "GA": "Georgia",
        "HI": "Hawaii",
        "ID": "Idaho",
        "IL": "Illinois",
        "IN": "Indiana",
        "IA": "Iowa",
        "KS": "Kansas",
        "KY": "Kentucky",
        "LA": "Louisiana",
        "ME": "Maine",
        "MD": "Maryland",
        "MA": "Massachusetts",
        "MI": "Michigan",
        "MN": "Minnesota",
        "MS": "Mississippi",
        "MO": "Missouri",
        "MT": "Montana",
        "NE": "Nebraska",
        "NV": "Nevada",
        "NH": "NewHampshire",
        "NJ": "NewJersey",
        "NM": "NewMexico",
        "NY": "NewYork",
        "NC": "NorthCarolina",
        "ND": "NorthDakota",
        "OH": "Ohio",
        "OK": "Oklahoma",
        "OR": "Oregon",
        "PA": "Pennsylvania",
        "RI": "RhodeIsland",
        "SC": "SouthCarolina",
        "SD": "SouthDakota",
        "TN": "Tennessee",
        "TX": "Texas",
        "UT": "Utah",
        "VT": "Vermont",
        "VA": "Virginia",
        "WA": "Washington",
        "WV": "WestVirginia",
        "WI": "Wisconsin",
        "WY": "Wyoming",
        "PR": "PuertoRico",
    }
    return names


def make_state_digit_to_code() -> dict[str, str]:
    codes: dict[str, str] = {
        "01": "AL",
        "02": "AK",
        "04": "AZ",
        "05": "AR",
        "06": "CA",
        "08": "CO",
        "09": "CT",
        "10": "DE",
        "11": "DC",
        "12": "FL",
        "13": "GA",
        "15": "HI",
        "16": "ID",
        "17": "IL",
        "18": "IN",
        "19": "IA",
        "20": "KS",
        "21": "KY",
        "22": "LA",
        "23": "ME",
        "24": "MD",
        "25": "MA",
        "26": "MI",
        "27": "MN",
        "28": "MS",
        "29": "MO",
        "30": "MT",
        "31": "NE",
        "32": "NV",
        "33": "NH",
        "34": "NJ",
        "35": "NM",
        "36": "NY",
        "37": "NC",
        "38": "ND",
        "39": "OH",
        "40": "OK",
        "41": "OR",
        "42": "PA",
        "44": "RI",
        "45": "SC",
        "46": "SD",
        "47": "TN",
        "48": "TX",
        "49": "UT",
        "50": "VT",
        "51": "VA",
        "53": "WA",
        "54": "WV",
        "55": "WI",
        "56": "WY",
        "72": "PR",
    }
    return codes


# Districts by state -- built from dra-types/lib/stateinfo.ts (11/04/2022)

districts_by_state: dict[str, Any] = {
    "AL": {"congress": 7, "upper": 35, "lower": 105},
    "AK": {"congress": 1, "upper": 20, "lower": 40},
    "AZ": {"congress": 9, "upper": 30, "lower": None},
    "AR": {"congress": 4, "upper": 35, "lower": 100},
    "CA": {"congress": 52, "upper": 40, "lower": 80},
    "CO": {"congress": 8, "upper": 35, "lower": 65},
    "CT": {"congress": 5, "upper": 36, "lower": 151},
    "DE": {"congress": 1, "upper": 21, "lower": 41},
    "FL": {"congress": 28, "upper": 40, "lower": 120},
    "GA": {"congress": 14, "upper": 56, "lower": 180},
    "HI": {"congress": 2, "upper": 25, "lower": 51},
    "ID": {"congress": 2, "upper": 35, "lower": None},
    "IL": {"congress": 17, "upper": 59, "lower": 118},
    "IN": {"congress": 9, "upper": 50, "lower": 100},
    "IA": {"congress": 4, "upper": 50, "lower": 100},
    "KS": {"congress": 4, "upper": 40, "lower": 125},
    "KY": {"congress": 6, "upper": 38, "lower": 100},
    "LA": {"congress": 6, "upper": 39, "lower": 105},
    "ME": {"congress": 2, "upper": 35, "lower": 151},
    "MD": {"congress": 8, "upper": 47, "lower": 67},
    "MA": {"congress": 9, "upper": 40, "lower": 160},
    "MI": {"congress": 13, "upper": 38, "lower": 110},
    "MN": {"congress": 8, "upper": 67, "lower": 134},
    "MS": {"congress": 4, "upper": 52, "lower": 122},
    "MO": {"congress": 8, "upper": 34, "lower": 163},
    "MT": {"congress": 2, "upper": 50, "lower": 100},
    "NE": {"congress": 3, "upper": 49, "lower": None},
    "NV": {"congress": 4, "upper": 21, "lower": 42},
    "NH": {"congress": 2, "upper": 24, "lower": 164},
    "NJ": {"congress": 12, "upper": 40, "lower": None},
    "NM": {"congress": 3, "upper": 42, "lower": 70},
    "NY": {"congress": 26, "upper": 63, "lower": 150},
    "NC": {"congress": 14, "upper": 50, "lower": 120},
    "ND": {"congress": 1, "upper": 47, "lower": 49},
    "OH": {"congress": 15, "upper": 33, "lower": 99},
    "OK": {"congress": 5, "upper": 48, "lower": 101},
    "OR": {"congress": 6, "upper": 30, "lower": 60},
    "PA": {"congress": 17, "upper": 50, "lower": 203},
    "RI": {"congress": 2, "upper": 38, "lower": 75},
    "SC": {"congress": 7, "upper": 46, "lower": 124},
    "SD": {"congress": 1, "upper": 35, "lower": 37},
    "TN": {"congress": 9, "upper": 33, "lower": 99},
    "TX": {"congress": 38, "upper": 31, "lower": 150},
    "UT": {"congress": 4, "upper": 29, "lower": 75},
    "VT": {"congress": 1, "upper": 13, "lower": 104},
    "VA": {"congress": 11, "upper": 40, "lower": 100},
    "WA": {"congress": 10, "upper": 49, "lower": None},
    "WV": {"congress": 2, "upper": 17, "lower": 100},
    "WI": {"congress": 8, "upper": 33, "lower": 99},
    "WY": {"congress": 1, "upper": 31, "lower": 62},
}


# TODO - Flesh this out
baseline_maps: dict[str, str] = {
    "AL": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "AR": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "AZ": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "CA": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "CO": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "CT": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "FL": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "GA": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "IA": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "IL": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "IN": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "KS": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "KY": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "LA": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "MA": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "MD": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "MI": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "MN": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "MO": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "MS": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "NC": "c62fa27b-1f4b-40ba-bcd7-9e2ca6f9df87",
    "NE": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "NJ": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "NM": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "NV": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "NY": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "OH": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "OK": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "OR": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "PA": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "SC": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "TN": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "TX": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "UT": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "VA": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "WA": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "WI": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
}

### END ###
